config/routes.rb
Rails.application.routes.draw do

  #put '/application/:id', to: 'application#like', as: 'like_post'
  #patch '/application/:post_id/:user_id', to: 'application#like', as: 'like_post'

  get '/application', to: 'application#like', as: 'like_post'
  post '/user_posts', to: 'criarpost#create'
  get '/perfil', to: 'perfil#perfil', as: 'perfil'
  get '/criarpost', to: 'criarpost#create', as: 'criarpost'

  #Pagina Inicial
  root 'application#render_def', as: 'application'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user_post.rb
class UserPost < ApplicationRecord
  self.table_name = "users_posts"
  # Campos da tabela users_posts
  attribute :id_post, :integer
  attribute :id_usuario, :integer
  attribute :descricao_post, :string
  attribute :like, :integer

  # Validações

end

app/controllers/ApplicationController.rb
class ApplicationController < ActionController::Base
  def render_def
    @user_posts = UserPost.all
    render 'application'
  end

  def like
    @user_post = UserPost.find(params[:post_id]) # encontra o post pelo id do post
    @user_post.like += 1 # incrementa o número de likes
    @user_post.save # salva o post atualizado
    redirect_to posts_path # redireciona para a página de posts
  end

end

app/controllers/PerfilController.rb
class PerfilController < ApplicationController
  def perfil
    @user_posts = UserPost.all
    render 'perfil'
  end
end

app/controllers/criarpost_controller.rb
class CriarpostController < ApplicationController
  def create
    render 'criarpost'
    post = UserPost.create(descricao_post: params[:descricao_post])
    # Faça qualquer outra ação necessária com o objeto "post"

    #redirect_to notice: 'Post criado com sucesso!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/criarpost.html.erb
<!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--=============== BOXICONS ===============-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
        <link rel="icon" href="https://img.icons8.com/?size=512&id=37210&format=png" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


        <title>Secrets | Home </title>
    </head>

	<style>

	/*=============== GOOGLE FONTS ===============*/
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap");
/*=============== VARIABLES CSS ===============*/
:root {
  --header-height: 3rem;

  /*========== Colors ==========*/
  --hue: 174;
  --sat: 63%;
  --first-color: hsl(var(--hue), var(--sat), 40%);
  --first-color-alt: hsl(var(--hue), var(--sat), 36%);
  --title-color: hsl(var(--hue), 12%, 15%);
  --text-color: hsl(var(--hue), 8%, 35%);
  --body-color: hsl(var(--hue), 100%, 99%);
  --container-color: #FFF;

  /*========== Font and typography ==========*/
  --body-font: 'Open Sans', sans-serif;
  --h1-font-size: 1.5rem;
  --normal-font-size: .938rem;
  --tiny-font-size: .625rem;

  /*========== z index ==========*/
  --z-tooltip: 10;
  --z-fixed: 100;
}

@media screen and (min-width: 968px) {
  :root {
    --h1-font-size: 2.25rem;
    --normal-font-size: 1rem;
  }
}

/*=============== BASE ===============*/
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: var(--header-height) 0 0 0;
  font-family: var(--body-font);
  font-size: var(--normal-font-size);
  background-color: var(--body-color);
  color: var(--text-color);
}

ul {
  list-style: none;
}

a {
  text-decoration: none;
}

img {
  max-width: 100%;
  height: auto;
}

/*=============== REUSABLE CSS CLASSES ===============*/
.section {
  padding: 4.5rem 0 2rem;
}

.section__title {
  font-size: var(--h1-font-size);
  color: var(--title-color);
  text-align: center;
  margin-bottom: 1.5rem;
}

.section__height {
  height: 100vh;
}

/*=============== LAYOUT ===============*/
.container {
  max-width: 968px;
  margin-left: 1rem;
  margin-right: 1rem;
}

/*=============== HEADER ===============*/
.header {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  background-color: var(--container-color);
  z-index: var(--z-fixed);
  transition: .4s;
}

/*=============== NAV ===============*/
.nav {
  height: var(--header-height);
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.nav__img {
  width: 32px;
  border-radius: 50%;
}

.nav__logo {
  color: var(--title-color);
  font-weight: 600;
}

@media screen and (max-width: 767px) {
  .nav__menu {
    position: fixed;
    bottom: 0;
    left: 0;
    background-color: var(--container-color);
    box-shadow: 0 -1px 12px hsla(var(--hue), var(--sat), 15%, 0.15);
    width: 100%;
    height: 4rem;
    padding: 0 1rem;
    display: grid;
    align-content: center;
    border-radius: 1.25rem 1.25rem 0 0;
    transition: .4s;
  }
}

.nav__list,
.nav__link {
  display: flex;
}

.nav__link {
  flex-direction: column;
  align-items: center;
  row-gap: 4px;
  color: var(--title-color);
  font-weight: 600;
}

.nav__list {
  justify-content: space-around;
}

.nav__name {
  font-size: var(--tiny-font-size);
  /* display: none;*/ /* Minimalist design, hidden labels */
}

.nav__icon {
  font-size: 1.5rem;
}

/*Active link*/
.active-link {
  position: relative;
  color: var(--first-color);
  transition: .3s;
}

/* Minimalist design, active link */
/* .active-link::before{
  content: '';
  position: absolute;
  bottom: -.5rem;
  width: 4px;
  height: 4px;
  background-color: var(--first-color);
  border-radius: 50%;
} */

/* Change background header */
.scroll-header {
  box-shadow: 0 1px 12px hsla(var(--hue), var(--sat), 15%, 0.15);
}

/*=============== MEDIA QUERIES ===============*/
/* For small devices */
/* Remove if you choose, the minimalist design */
@media screen and (max-width: 320px) {
  .nav__name {
    display: none;
  }
}

/* For medium devices */
@media screen and (min-width: 576px) {
  .nav__list {
    justify-content: center;
    column-gap: 3rem;
  }
}

@media screen and (min-width: 767px) {
  body {
    margin: 0;
  }
  .section {
    padding: 7rem 0 2rem;
  }
  .nav {
    height: calc(var(--header-height) + 1.5rem); /* 4.5rem */
  }
  .nav__img {
    display: none;
  }
  .nav__icon {
    display: none;
  }
  .nav__name {
    font-size: var(--normal-font-size);
    /* display: block; */ /* Minimalist design, visible labels */
  }
  .nav__link:hover {
    color: var(--first-color);
  }

  /* First design, remove if you choose the minimalist design */
  .active-link::before {
    content: '';
    position: absolute;
    bottom: -.75rem;
    width: 4px;
    height: 4px;
    background-color: var(--first-color);
    border-radius: 50%;
  }

  /* Minimalist design */
  /* .active-link::before{
      bottom: -.75rem;
  } */
}

/* For large devices */
@media screen and (min-width: 1024px) {
  .container {
    margin-left: auto;
    margin-right: auto;
  }
}

/* .container {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh; } /* Ajuste a altura conforme necessário */

.square-card {
  width: 300px; /* Ajuste o tamanho conforme necessário */
  height: 300px;
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;

  /* Estilos do card original */
  background-color: #FFF;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  margin-bottom: 1.5rem;
  padding: 1rem;
}

.square-card__content {
  padding: 1rem;
}

.square-card__text {
  color: #333;
  font-size: 1rem;
  line-height: 1.5;
}


.square-card {
  /* Estilos do card original */
  width: 300px; /* Ajuste o tamanho conforme necessário */
  height: 200px;
  display: center;
  align-items: center;
  justify-content: center;
  text-align: center;
  background-color: #FFF;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
  margin-bottom: 1.5rem;
  padding: 1rem;

  /* Adicionado para centralizar horizontalmente */
  margin: 0 auto;

    margin-bottom: 3rem;
}

.square-card__content {
  padding: 1rem;
}


.input-wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 1rem;
}

.input-wrapper textarea {
  width: 100%;
  max-width: 100%;
  height: 100px; /* Ajuste a altura conforme necessário */
  padding: 0.5rem;
  border-radius: 4px;
  border: 1px solid #ccc;
}

.button-wrapper {
  text-align: center;
}

.button-wrapper button {
  /* Estilos para o botão */
}

.square-card button {
  /* Removendo estilos padrão do botão */
  border: none;
  background: none;
  padding: 0;
  margin: 0;

    /* Centralizando o botão no card */
  display: block;
  margin: 0 auto;
}

.square-card button .fa-heart {
  /* Estilizando o ícone de coração */
  color: red;
  font-size: 14px;
}

.send-button {
  /* Estilizando o botão */
  border: none;
  background-color: #0088cc;
  color: black;
  padding: 12px 20px;
  border-radius: 32px;
  font-size: 16px;
  cursor: pointer;
}

.send-button .fa-paper-plane {
  /* Estilizando o ícone de avião de papel */
  margin-right: 8px;
}

button:hover {
  background-color: #265df2;
}
button.show-modal,
.modal-box {
  position: fixed;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
}
section.active .show-modal {
  display: none;
}
.overlay {
  position: fixed;
  height: 100%;
  width: 100%;
  background: rgba(0, 0, 0, 0.3);
  opacity: 0;
  pointer-events: none;
}
section.active .overlay {
  opacity: 1;
  pointer-events: auto;
}
.modal-box {
  display: flex;
  flex-direction: column;
  align-items: center;
  max-width: 380px;
  width: 100%;
  padding: 30px 20px;
  border-radius: 24px;
  background-color: #fff;
  opacity: 0;
  pointer-events: none;
  transition: all 0.3s ease;
  transform: translate(-50%, -50%) scale(1.2);
}
section.active .modal-box {
  opacity: 1;
  pointer-events: auto;
  transform: translate(-50%, -50%) scale(1);
}
.modal-box i {
  font-size: 70px;
  color: #4070f4;
}
.modal-box h2 {
  margin-top: 20px;
  font-size: 25px;
  font-weight: 500;
  color: #333;
}
.modal-box h3 {
  font-size: 16px;
  font-weight: 400;
  color: #333;
  text-align: center;
}
.modal-box .buttons {
  margin-top: 25px;
}
.modal-box button {
  font-size: 14px;
  padding: 6px 12px;
  margin: 0 10px;
}

	</style>
    <body>

        <!--=============== Cabeçalho (Botões) ===============-->
        <header class="header" id="header">
            <nav class="nav container">
                <a href="#" class="nav__logo">SECRETS</a>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item">
                  <a href="<%= application_path %>" class="nav__link">
                      <i class='bx bx-user nav__icon'></i>
                      <span class="nav__name">Inicio</span>
                  </a>
                        </li>

                  <a href="<%= perfil_path %>" class="nav__link">
                      <i class='bx bx-user nav__icon'></i>
                      <span class="nav__name">Minhas Publicações</span>
                  </a>


                        <li class="nav__item">
                            <a href="#skills" class="nav__link">
                                <i class='bx bx-book-alt nav__icon'></i>
                                <span class="nav__name">Meus Posts</span>
                            </a>
                        </li>

                        <li class="nav__item">
                            <a href="#portfolio" class="nav__link">
                                <i class='bx bx-briefcase-alt nav__icon'></i>
                                <span class="nav__name">Instruções</span>
                            </a>
                        </li>

                        <li class="nav__item">
                            <a href="#contactme" class="nav__link">
                                <i class='bx bx-message-square-detail nav__icon'></i>
                                <span class="nav__name">Mensagens</span>
                            </a>
                        </li>
                    </ul>
                </div>

                <img src="assets/img/perfil.png" alt="" class="nav__img">
            </nav>
        </header>

        <main>


          <!--=============== Meus Posts ===============-->
          <section class="container section section__height" id="skills">
            <h2 class="section__title">Meus Posts</h2>
            <div class="square-card">
                <div class="square-card__content">
                <form action="/user_posts" method="POST">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <div class="input-wrapper">
                    <textarea name="descricao_post" placeholder="Digite seu texto"></textarea>
                    </div>
                    <button class="send-button"><i class="fa fa-paper-plane"></i> Enviar</button>
                </form>
                </div>
            </div>
            </section>



        <script>



        </script>


    </body>
</html>

app/views/application/perfil.html.erb
<!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--=============== BOXICONS ===============-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
        <link rel="icon" href="https://img.icons8.com/?size=512&id=37210&format=png" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


        <title>Secrets | Home </title>
    </head>

	<style>

	/*=============== GOOGLE FONTS ===============*/
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap");
/*=============== VARIABLES CSS ===============*/
:root {
  --header-height: 3rem;

  /*========== Colors ==========*/
  --hue: 174;
  --sat: 63%;
  --first-color: hsl(var(--hue), var(--sat), 40%);
  --first-color-alt: hsl(var(--hue), var(--sat), 36%);
  --title-color: hsl(var(--hue), 12%, 15%);
  --text-color: hsl(var(--hue), 8%, 35%);
  --body-color: hsl(var(--hue), 100%, 99%);
  --container-color: #FFF;

  /*========== Font and typography ==========*/
  --body-font: 'Open Sans', sans-serif;
  --h1-font-size: 1.5rem;
  --normal-font-size: .938rem;
  --tiny-font-size: .625rem;

  /*========== z index ==========*/
  --z-tooltip: 10;
  --z-fixed: 100;
}

@media screen and (min-width: 968px) {
  :root {
    --h1-font-size: 2.25rem;
    --normal-font-size: 1rem;
  }
}

/*=============== BASE ===============*/
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: var(--header-height) 0 0 0;
  font-family: var(--body-font);
  font-size: var(--normal-font-size);
  background-color: var(--body-color);
  color: var(--text-color);
}

ul {
  list-style: none;
}

a {
  text-decoration: none;
}

img {
  max-width: 100%;
  height: auto;
}

/*=============== REUSABLE CSS CLASSES ===============*/
.section {
  padding: 4.5rem 0 2rem;
}

.section__title {
  font-size: var(--h1-font-size);
  color: var(--title-color);
  text-align: center;
  margin-bottom: 1.5rem;
}

.section__height {
  height: 100vh;
}

/*=============== LAYOUT ===============*/
.container {
  max-width: 968px;
  margin-left: 1rem;
  margin-right: 1rem;
}

/*=============== HEADER ===============*/
.header {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  background-color: var(--container-color);
  z-index: var(--z-fixed);
  transition: .4s;
}

/*=============== NAV ===============*/
.nav {
  height: var(--header-height);
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.nav__img {
  width: 32px;
  border-radius: 50%;
}

.nav__logo {
  color: var(--title-color);
  font-weight: 600;
}

@media screen and (max-width: 767px) {
  .nav__menu {
    position: fixed;
    bottom: 0;
    left: 0;
    background-color: var(--container-color);
    box-shadow: 0 -1px 12px hsla(var(--hue), var(--sat), 15%, 0.15);
    width: 100%;
    height: 4rem;
    padding: 0 1rem;
    display: grid;
    align-content: center;
    border-radius: 1.25rem 1.25rem 0 0;
    transition: .4s;
  }
}

.nav__list,
.nav__link {
  display: flex;
}

.nav__link {
  flex-direction: column;
  align-items: center;
  row-gap: 4px;
  color: var(--title-color);
  font-weight: 600;
}

.nav__list {
  justify-content: space-around;
}

.nav__name {
  font-size: var(--tiny-font-size);
  /* display: none;*/ /* Minimalist design, hidden labels */
}

.nav__icon {
  font-size: 1.5rem;
}

/*Active link*/
.active-link {
  position: relative;
  color: var(--first-color);
  transition: .3s;
}

/* Minimalist design, active link */
/* .active-link::before{
  content: '';
  position: absolute;
  bottom: -.5rem;
  width: 4px;
  height: 4px;
  background-color: var(--first-color);
  border-radius: 50%;
} */

/* Change background header */
.scroll-header {
  box-shadow: 0 1px 12px hsla(var(--hue), var(--sat), 15%, 0.15);
}

/*=============== MEDIA QUERIES ===============*/
/* For small devices */
/* Remove if you choose, the minimalist design */
@media screen and (max-width: 320px) {
  .nav__name {
    display: none;
  }
}

/* For medium devices */
@media screen and (min-width: 576px) {
  .nav__list {
    justify-content: center;
    column-gap: 3rem;
  }
}

@media screen and (min-width: 767px) {
  body {
    margin: 0;
  }
  .section {
    padding: 7rem 0 2rem;
  }
  .nav {
    height: calc(var(--header-height) + 1.5rem); /* 4.5rem */
  }
  .nav__img {
    display: none;
  }
  .nav__icon {
    display: none;
  }
  .nav__name {
    font-size: var(--normal-font-size);
    /* display: block; */ /* Minimalist design, visible labels */
  }
  .nav__link:hover {
    color: var(--first-color);
  }

  /* First design, remove if you choose the minimalist design */
  .active-link::before {
    content: '';
    position: absolute;
    bottom: -.75rem;
    width: 4px;
    height: 4px;
    background-color: var(--first-color);
    border-radius: 50%;
  }

  /* Minimalist design */
  /* .active-link::before{
      bottom: -.75rem;
  } */
}

/* For large devices */
@media screen and (min-width: 1024px) {
  .container {
    margin-left: auto;
    margin-right: auto;
  }
}

/* .container {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh; } /* Ajuste a altura conforme necessário */

.square-card {
  width: 300px; /* Ajuste o tamanho conforme necessário */
  height: 300px;
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;

  /* Estilos do card original */
  background-color: #FFF;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  margin-bottom: 1.5rem;
  padding: 1rem;
}

.square-card__content {
  padding: 1rem;
}

.square-card__text {
  color: #333;
  font-size: 1rem;
  line-height: 1.5;
}


.square-card {
  /* Estilos do card original */
  width: 300px; /* Ajuste o tamanho conforme necessário */
  height: 200px;
  display: center;
  align-items: center;
  justify-content: center;
  text-align: center;
  background-color: #FFF;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
  margin-bottom: 1.5rem;
  padding: 1rem;

  /* Adicionado para centralizar horizontalmente */
  margin: 0 auto;

    margin-bottom: 3rem;
}

.square-card__content {
  padding: 1rem;
}


.input-wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 1rem;
}

.input-wrapper textarea {
  width: 100%;
  max-width: 100%;
  height: 100px; /* Ajuste a altura conforme necessário */
  padding: 0.5rem;
  border-radius: 4px;
  border: 1px solid #ccc;
}

.button-wrapper {
  text-align: center;
}

.button-wrapper button {
  /* Estilos para o botão */
}

.square-card button {
  /* Removendo estilos padrão do botão */
  border: none;
  background: none;
  padding: 0;
  margin: 0;

    /* Centralizando o botão no card */
  display: block;
  margin: 0 auto;
}

.square-card button .fa-heart {
  /* Estilizando o ícone de coração */
  color: red;
  font-size: 14px;
}

.send-button {
  /* Estilizando o botão */
  border: none;
  background-color: #0088cc;
  color: black;
  padding: 12px 20px;
  border-radius: 32px;
  font-size: 16px;
  cursor: pointer;
}

.send-button .fa-paper-plane {
  /* Estilizando o ícone de avião de papel */
  margin-right: 8px;
}

button:hover {
  background-color: #265df2;
}
button.show-modal,
.modal-box {
  position: fixed;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
}
section.active .show-modal {
  display: none;
}
.overlay {
  position: fixed;
  height: 100%;
  width: 100%;
  background: rgba(0, 0, 0, 0.3);
  opacity: 0;
  pointer-events: none;
}
section.active .overlay {
  opacity: 1;
  pointer-events: auto;
}
.modal-box {
  display: flex;
  flex-direction: column;
  align-items: center;
  max-width: 380px;
  width: 100%;
  padding: 30px 20px;
  border-radius: 24px;
  background-color: #fff;
  opacity: 0;
  pointer-events: none;
  transition: all 0.3s ease;
  transform: translate(-50%, -50%) scale(1.2);
}
section.active .modal-box {
  opacity: 1;
  pointer-events: auto;
  transform: translate(-50%, -50%) scale(1);
}
.modal-box i {
  font-size: 70px;
  color: #4070f4;
}
.modal-box h2 {
  margin-top: 20px;
  font-size: 25px;
  font-weight: 500;
  color: #333;
}
.modal-box h3 {
  font-size: 16px;
  font-weight: 400;
  color: #333;
  text-align: center;
}
.modal-box .buttons {
  margin-top: 25px;
}
.modal-box button {
  font-size: 14px;
  padding: 6px 12px;
  margin: 0 10px;
}

	</style>
    <body>

        <!--=============== Cabeçalho (Botões) ===============-->
        <header class="header" id="header">
            <nav class="nav container">
                <a href="#" class="nav__logo">SECRETS</a>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item">
                  <a href="<%= application_path %>" class="nav__link">
                      <i class='bx bx-user nav__icon'></i>
                      <span class="nav__name">Inicio</span>
                  </a>
                        </li>

                    <a href="<%= perfil_path %>" class="nav__link">
                        <i class='bx bx-user nav__icon'></i>
                        <span class="nav__name">Minhas Publicações</span>
                    </a>

                        <li class="nav__item">
                            <a href="<%= criarpost_path %>" class="nav__link">
                                <i class='bx bx-user nav__icon'></i>
                                <span class="nav__name">Criar um Post</span>
                            </a>
                        </li>

                        <li class="nav__item">
                            <a href="#portfolio" class="nav__link">
                                <i class='bx bx-briefcase-alt nav__icon'></i>
                                <span class="nav__name">Instruções</span>
                            </a>
                        </li>

                        <li class="nav__item">
                            <a href="#contactme" class="nav__link">
                                <i class='bx bx-message-square-detail nav__icon'></i>
                                <span class="nav__name">Mensagens</span>
                            </a>
                        </li>
                    </ul>
                </div>

                <img src="assets/img/perfil.png" alt="" class="nav__img">
            </nav>
        </header>

        <main>

            <!--=============== Perfil ===============-->


            <section class="container section section__height" id="about">
                <h2 class="section__title">Minhas Publicações</h2>

                <!--=============== Cards dos posts ===============-->
                <% @user_posts.each do |post| %>
                        <div class="square-card">
                            <div class="square-card__content">
                            <p class="square-card__text"><%= post.descricao_post %></p>
                            </div>
                            <button class="like-button"><i class="fa fa-heart"></i></button> <%# Botão de curtir. %>
                        </div>
                        <% end %>
            </section>



            <!--=============== Adcionar opções do pefil aqui ===============-->



        </main>

        <!--=============== MAIN JS ===============-->
        <script>





        </script>


    </body>
</html>